"""added unique child id code to child model

Revision ID: 8dee629a39ce
Revises: 31c8850efe56
Create Date: 2023-12-05 19:33:36.738492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dee629a39ce'
down_revision: Union[str, None] = '31c8850efe56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('unique_child_id_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'unique_child_id_code')
    # ### end Alembic commands ###
